### PR TITLE
Add Fritzing part and example circuit

### PR DESCRIPTION
**Pull request by soswow**
Would be good if you first verify everything. Especially names of pins on the part and their description and example circuit itself.

### CODE REVIEW

**Comment by soswow** [comment]
when you review it, i can push it to https://github.com/fritzing/fritzing-parts/pulls for wider community

**Comment by soswow** [comment]
@teemuatlut lol. last 15 minutes - thats what I was searching for. No. https://github.com/fritzing/fritzing-parts/issues/32
I even thought making it. found best svg available http://reprap.org/mediawiki/images/6/6d/Rampswire14.svg
It's a bit too much as side-stepping-project. =)

**Comment by teemuatlut** [comment]
I seem to recall that this is where I hit a dead end as well last year when I looked into this.
The thing is that most of the people who use the drivers use it with RAMPS board or something similar.
So maybe I'll add just PNG to show a barebones wiring setup but will need to look into making a more complete and more suitable image later. Perhaps a simplified RAMPS board such as the one shown in your image wouldn't be too time consuming to create.

Let me know if you'd like to take a crack at it and I'll hold off merging part of this PR.

**Comment by soswow** [comment]
m-m-m. Ok. I might misunderstood what you had in your TODO. You might not need a fritzing part itself in your PR. IT's probably better to push to mentioned repo.
What I am saying they already have parts in standard collection for A4988 and DRV8825:
screen shot 2018-06-09 at 10 48 19 pm

So my work here wasn't all that useless. =)

Maybe you can help me with double-checking what I have here anyway, so I can proceed with pushing this part to fritzing official parts repo?
And I might give it a go and do simplified RAMPS part.

**Comment by teemuatlut** [comment]
The TMC2130 SilentStepStick part is great!
And if you wish to go ahead with creating a simplified RAMPS1.4, then the wiring itself is quite trivial at that point.
The goal in the TODO list was a "complete" wiring setup for typical 4x TMC2130 configuration.

The pins picked in the examples are a bit silly for stand alone operation because they correspond with stepper X in the RAMPS1.4 board definition.

**Comment by soswow** [comment]
Also, what do you think about the way I tried to convey the fact the face on top is actually a back side with all the components (donated with semi-transparency) are on the other side?

Also, I don't have actual connections for SPI mode bridge pads, CFG pads and DIAG whole. I think if I want to make it official part, these things need to be added =\

**Comment by teemuatlut** [comment]
Would be nice to have the pads and everything but ultimately it's up to you if you want to add them.

I'd say it's a compromise solution but it'll have to work. You could add the text "TOP" to the model to match the actual PCB silkscreen.

**Comment by soswow** [comment]
> You could add the text "TOP" to the model to match the actual PCB silkscreen.
Didn't understand exactly what do you mean.

**Comment by teemuatlut** [comment]
On the actual StepStick it says
>SilentStepStick
>TMC2130
>TOP

in white lettering. That's called the silkscreen. You could add that to the model to better indicate how the driver gets orientated.

**Pull request merged**
