### PR TITLE
Maybe stick to version 2.2.0?

### PR DESCRIPTION
**Pull request by thinkyhead**
I bumped the version in case you wanted to hold the change till the next release. But if you're merging now, then might as well keep it at 2.2.0.

### CODE REVIEW

**Comment by teemuatlut** [comment]
I'll update the versions the next time I do a new release.

**Comment by thinkyhead** [comment]
If it wasn't clear, this fixes the version — setting it back to 2.2.0.

**Comment by thinkyhead** [comment]
Backward-compatibility added.

**Comment by teemuatlut** [comment]
v2.2.1 released that restores [backward compatibility](https://github.com/teemuatlut/TMC2130Stepper/commit/026206d7d3d2c3bec4bda6de36bc73202ac341a5).

**Pull request closed without merging**
